### ISSUE TITLE
using cadence with a function that invokes its callback multiple times...

### ISSUE THREAD

**Issue by mrose17** [bigeasy/cadence#271]
if you look at https://github.com/TheThingSystem/node-arp-a you'll see that one of the functions it defines looks like this:

        ifTable(function(err, entry) {
            if (!!err) return console.log('error.')
            if (!entry) return console.log('done.')
            console.log('got entry, still working...')
        }

so the callback is invoked once for each entry, plus one more time to signal the end.

i want to wrap this in a cadence. based on the docs, i thought that this was the ticket:

        var emitter = new require('events').EventEmitter()
          , ifTable = require('arp-a').ifTable

        async(function () {
            ifTable(function(err, entry) {
                if (!!err) return emitter.emit('error', err)
                if (!entry) return emitter.emit('end')
                if (entry.name == process.env.PERSEUS_WIFI_IFACE) emitter.emit('data', entry.mac)
            })

            emitter.on('data', async(-1, []))
            emitter.on('end', async(-1))
            emitter.on('error', async(Error))
        }, function (data) {
            // this is never called
        })

however, as the comment indicates, the second function is never invoked. what am i doing wrong.

thanks!

**Comment by bigeasy** [comment]
Wow. Yes, that's a great solution. Why doesn't it work? Maybe we can screen share or something?

**Comment by mrose17** [comment]
sorry i didn't reply earlier. i don't know what it works. check out https://github.com/mrose17/auxiliary-automation-unit/blob/master/cadence-event-test.js -- get the repo and `npm install -l` and then `node cadence-event-test.js` and you'll see what i see!

**Comment by bigeasy** [comment]
Are we still working on this problem, or have you moved on from it? Cadence has a new API for `EventEmitter`, this is the now stable Cadence Redux we've been using for, well, seems like months now.

**Comment by mrose17** [comment]
i don't think so. i'll try out the `EventEmitter` when i've got a few cycles, thanks!
